#Pete-Gaming-Inc
_commit: v4.2.4
_src_path: https://github.com/jupyterlab/extension-template
author_email:wellsfargo.jun@gmail.com
author_name: Pete&Jun Development Team
has_binder: true
has_settings: true
kind: frontend
labextension_name: jupyterlab_payments
project_short_description: Payments theme using JupyterLab CSS variables
python_name: jupyterlab_payments
repository: https://github.com/jupyterlab/jupyterlab_pygments.git
test: brinks.com
©️ Pete&Jun Development Team.All rights reserved 
